### ISSUE TITLE
Keyboard opens when slider is used.

### ISSUE THREAD

**Issue by SimmelFlo** [hijaaack/JB.TcHmiSimpleRangeSlider#1]
Hello @hijaaack,
is there a way to prevent the Keyboard from opening when slider is used?
![image](https://github.com/hijaaack/JB.TcHmiSimpleRangeSlider/assets/108086424/5396bc67-de8f-4c81-ba9f-98966b89bb00)

I am using TcHmi version 1.12.760.37.

Thanks in Advance!

**Comment by hijaaack** [comment]
Hi @SimmelFlo, I will have a look but not sure if there is an easy fix or not due to the slider is an "input" element and the new SystemKeyboard seems to open on all "input" elements.

**Comment by hijaaack** [comment]
@SimmelFlo, Solved in the new version 1.1.0 of the control.
